logstash:
  logstashPipeline: 
    logstash.conf: |
      input {
        http {
          port      => 8080
        }
      }
      filter {
        prune {
          blacklist_values => {
            "log" => "(MYSQL_PASSWORD|AWS_SECRET)"
          }
        }
      }
      output {
        elasticsearch {
          hosts => "hostname"
          data_stream => "true"
        }
      }