logstash:
  logstashPipeline: 
    logstash.conf: |
      input {
        http {
          port      => 8080
        }
      }
      filter {
        mutate {
          rename => { "[kubernetes][labels][app.kubernetes.io/instance]" => "[kubernetes][labels][mariancapo]" }
        }
      }
      output {
        stdout { codec => rubydebug }
      }