logstash:
  logstashPipeline: 
    logstash.conf: |
      input {
        http {
          port      => 8080
        }
      }
      filter {
        mutate {
          rename => { 
            "[kubernetes][labels][app.kubernetes.io/instance]" => "[kubernetes][labels][instance]" 
            "[kubernetes][labels][app.kubernetes.io/component]" => "[kubernetes][labels][component]" 
            "[kubernetes][labels][app.kubernetes.io/name]" => "[kubernetes][labels][name]" 
            "[kubernetes][labels][app.kubernetes.io/managed-by]" => "[kubernetes][labels][managed-by]" 
          }
        }
      }
      output {
        stdout { codec => rubydebug }
        elasticsearch {
          hosts => "elasticsearch-master"
        }
      }