logstash:
  logstashPipeline: 
    logstash.conf: |
      input {
        http {
          port      => 8080
        }
      }
      output {
        stdout { codec => rubydebug }
        elasticsearch {
          hosts => "elasticsearch-master"
        }
      }