logstash:
  logstashPipeline: 
    logstash.conf: |
      input {
        http {
          add_field => { "[@metadata][input-http]" => "" }
          port      => 8080
        }
      }
      filter {
        if [@metadata][input-http] {
          date {
            match => [ "date", "UNIX" ]
            remove_field => [ "date" ]
          }
          mutate {
            remove_field => ["headers","host"]
          }
        }
      }
      output {
        elasticsearch {
          hosts => "elasticsearch-master"
          data_stream => "true"
        }
      }