logstash:
  logstashPipeline: 
    logstash.conf: |
      input {
        http {
          add_field => { "[@metadata][input-http]" => "" }
          port      => 8080
        }
      }
      filter {
        date {
          match => [ "date", "UNIX" ]
          remove_field => [ "date" ]
        }
        mutate {
          remove_field => ["headers","host", "app"]
          '[kubernetes][labels][app]'   => '[kubernetes][labels][app.kubernetes.io/name]'
          '[kubernetes][labels][chart]' => '[kubernetes][labels][helm.sh/chart]'
        }
      }
      output {
        elasticsearch {
          hosts => "elasticsearch-master"
          data_stream => "true"
        }
      }