apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: entrypoint
  template:
    metadata:
      labels:
        role: entrypoint
    spec:
      containers:
      - image: agustinnormand/tpi_entrypoint:9d699ff443c3aecc847b43ac360d645bbaca280a
        imagePullPolicy: IfNotPresent
        name: entrypoint
