apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: entrypoint
  template:
    metadata:
      labels:
        role: entrypoint
    spec:
      containers:
      - image: agustinnormand/tpi_entrypoint:5bd7f0a4fb62399b04d351d4b158d328c08d91d0
        imagePullPolicy: IfNotPresent
        name: entrypoint
