apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: entrypoint
  template:
    metadata:
      labels:
        role: entrypoint
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-cluster-app
        - name: RABBIT_USER
          value: admin
        - name: RABBIT_PWD
          value: agusmarian
        - name: STATUS_SERVICE_URL
          value: http://status-worker-service
        image: agustinnormand/tpi_entrypoint:ec400bc5dfe28ce36c1714d97a653bede5ef9689
        imagePullPolicy: IfNotPresent
        name: entrypoint
        ports:
        - containerPort: 8080
