apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: entrypoint
  template:
    metadata:
      labels:
        role: entrypoint
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-service
        image: agustinnormand/tpi_entrypoint:57abb6bc1653d57590ed4d1d885ad253bb80da6c
        imagePullPolicy: IfNotPresent
        name: entrypoint
        ports:
        - containerPort: 8080
