apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: entrypoint
  template:
    metadata:
      labels:
        role: entrypoint
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-service
        - name: STATUS_SERVICE_URL
          value: http://status-worker-service
        image: agustinnormand/tpi_entrypoint:d8c08a7ff57ecef4c9b0e8a2ef72ac46dd27a169
        imagePullPolicy: IfNotPresent
        name: entrypoint
        ports:
        - containerPort: 8080
