apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: entrypoint-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: entrypoint
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Object
    object:
      metric:
        name: rate_nginx_ingress_controller_nginx_process_requests_total
      describedObject:
        apiVersion: v1
        kind: Service
        name: ingress-nginx-app-controller
      target:
        type: Value
        averageValue: 300m