apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: entrypoint
  template:
    metadata:
      labels:
        role: entrypoint
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-service
        - name: STATUS_SERVICE_URL
          value: status-worker-service
        image: agustinnormand/tpi_entrypoint:6ad63b667b55c11491364e7d730809af673521b9
        imagePullPolicy: IfNotPresent
        name: entrypoint
        ports:
        - containerPort: 8080
