apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: entrypoint
  template:
    metadata:
      labels:
        role: entrypoint
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-service
        image: agustinnormand/tpi_entrypoint:72d9aed2db3e83ede0c5f7072606902a6b2926dd
        imagePullPolicy: IfNotPresent
        name: entrypoint
        ports:
        - containerPort: 8080
