apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: status-worker
  template:
    metadata:
      labels:
        role: status-worker
    spec:
      containers:
      - image: agustinnormand/tpi_status-worker:5bd7f0a4fb62399b04d351d4b158d328c08d91d0
        imagePullPolicy: IfNotPresent
        name: status-worker
