apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaml-manager
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: yaml-manager
  template:
    metadata:
      labels:
        role: yaml-manager
    spec:
      containers:
      - image: agustinnormand/tpi_yaml-manager:5bd7f0a4fb62399b04d351d4b158d328c08d91d0
        imagePullPolicy: IfNotPresent
        name: yaml-manager
