apiVersion: v1
kind: Service
metadata:
  name: receptionist-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    role: receptionist
