apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaml-manager
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: yaml-manager
  template:
    metadata:
      labels:
        role: yaml-manager
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-service
        image: agustinnormand/tpi_yaml-manager:5b9180aeab766743c7aa7ff9424554dd2fff053b
        imagePullPolicy: IfNotPresent
        name: yaml-manager
