apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaml-manager
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: yaml-manager
  template:
    metadata:
      labels:
        role: yaml-manager
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-cluster-app
        - name: RABBIT_USER
          value: admin
        - name: RABBIT_PWD
          value: agusmarian
        image: agustinnormand/tpi_yaml-manager:20256e2728758073dd0f80fa37506ff38405fc1d
        imagePullPolicy: IfNotPresent
        name: yaml-manager
