apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-applier
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: cluster-applier
  template:
    metadata:
      labels:
        role: cluster-applier
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-service
        image: agustinnormand/tpi_cluster_applier:9007e121b6f572a4524f809a2df48e10989cbd1e
        imagePullPolicy: IfNotPresent
        name: cluster-applier
