apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-applier
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: cluster-applier
  template:
    metadata:
      labels:
        role: cluster-applier
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-cluster-app
        - name: RABBIT_USER
          value: admin
        - name: RABBIT_PWD
          value: agusmarian
        image: agustinnormand/tpi_cluster_applier:796fffab907bf4e83638a2582964a3394fc17251
        imagePullPolicy: IfNotPresent
        name: cluster-applier
