apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cluster-applier-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cluster-applier
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Object
    object:
      metric:
        name: rabbitmq_queue_messages_cluster-appliers
      describedObject:
        apiVersion: v1
        kind: Service
        name: rabbitmq-cluster-app
      target:
        type: Value
        value: 10