apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: status-worker
  template:
    metadata:
      labels:
        role: status-worker
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-service
        - name: REDIS_HOST
          value: redis-cluster
        image: agustinnormand/tpi_status-worker:68ab92a0ecf169fb1bd124fe77fa398159d4413e
        imagePullPolicy: IfNotPresent
        name: status-worker
