apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: status-worker
  template:
    metadata:
      labels:
        role: status-worker
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-service
        - name: REDIS_HOST
          value: redis-cluster-app
        image: agustinnormand/tpi_status-worker:9683de6d51a16817aad3c7f1d251c1fa8ea8a79d
        imagePullPolicy: IfNotPresent
        name: status-worker
