2021/08/04 22:19:30 nil value at `valueFrom.configMapKeyRef.name` ignored in mutation attempt
2021/08/04 22:19:30 nil value at `valueFrom.secretKeyRef.name` ignored in mutation attempt
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: status-worker
  template:
    metadata:
      labels:
        role: status-worker
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-service
        - name: REDIS_HOST
          value: redis-cluster-app
        - name: REDIS_PWD
          secretKeyRef:
            key: redis-password
            name: redis-cluster-app
          valueFrom: null
        image: agustinnormand/tpi_status-worker:be7d913a618ce88e97b612c3f5e58ef563ba3785
        imagePullPolicy: IfNotPresent
        name: status-worker
