apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: status-worker
  template:
    metadata:
      labels:
        role: status-worker
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8080"
        - name: RABBIT_HOST
          value: rabbitmq-cluster-app
        - name: RABBIT_USER
          value: admin
        - name: RABBIT_PWD
          value: agusmarian
        - name: REDIS_HOST
          value: redis-cluster-app
        - name: REDIS_PWD
          value: agusmarian
        image: agustinnormand/tpi_status-worker:ec400bc5dfe28ce36c1714d97a653bede5ef9689
        imagePullPolicy: IfNotPresent
        name: status-worker
