apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: status-worker
  template:
    metadata:
      labels:
        role: status-worker
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8080"
        - name: RABBIT_HOST
          value: rabbitmq-service
        - name: REDIS_HOST
          value: redis-cluster-app
        - name: REDIS_PWD
          value: agusmarian
        image: agustinnormand/tpi_status-worker:08809e5add04165a8e0cb9f196c11b89f23e473a
        imagePullPolicy: IfNotPresent
        name: status-worker
