apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: status-worker
  template:
    metadata:
      labels:
        role: status-worker
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-service
        - name: REDIS_HOST
          value: redis-service
        image: agustinnormand/tpi_status-worker:5b9180aeab766743c7aa7ff9424554dd2fff053b
        imagePullPolicy: IfNotPresent
        name: status-worker
