apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: status-worker
  template:
    metadata:
      labels:
        role: status-worker
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq-service
        - name: REDIS_HOST
          value: redis-service
        image: agustinnormand/tpi_status-worker:715229782bdd89a9ea9ac8ca8625dd318b5f3223
        imagePullPolicy: IfNotPresent
        name: status-worker
