apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: status-worker
  template:
    metadata:
      labels:
        role: status-worker
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: 8080
        - name: RABBIT_HOST
          value: rabbitmq-service
        - name: REDIS_HOST
          value: redis-cluster-app
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis-cluster-app
        image: agustinnormand/tpi_status-worker:5512fa649a3608dd221865afb2b013eb07c8536c
        imagePullPolicy: IfNotPresent
        name: status-worker
