apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: status-worker
  template:
    metadata:
      labels:
        role: status-worker
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis-service
        image: agustinnormand/tpi_status-worker:749bb0b66e46eb32a2cc8ced401b2d59eb08109e
        imagePullPolicy: IfNotPresent
        name: status-worker
