apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    component: rabbitmq
spec:
  selector:
    component: rabbitmq
  ports:
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: web
    port: 15692
    protocol: TCP
    targetPort: 15692
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
