apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: redis
  name: redis-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
      - image: redis:6.2.4-alpine
        name: redis
        ports:
        - containerPort: 6379
          name: redis-port
          protocol: TCP
