apiVersion: v1
kind: Service
metadata:
  name: redis-service
  annotations:
  labels:
    component: redis
spec:
  selector:
    component: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
