apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaml-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      role: yaml-manager
  template:
    metadata:
      labels:
        role: yaml-manager
    spec:
      containers:
      - name: yaml-manager
        image: image_tag
        imagePullPolicy: IfNotPresent        
        #ports:
        #- containerPort: 8080
        #readinessProbe:
        #  httpGet:
        #    path: /health
        #    port: 8080
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
        #livenessProbe:
        #  tcpSocket:
        #    port: 8080
        #  initialDelaySeconds: 15
        #  periodSeconds: 20
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
