apiVersion: v2
name: ingress-nginx-subchart
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: ingress-nginx
  version: 3.35.0
  repository: https://kubernetes.github.io/ingress-nginx