rabbitmq:
  replicaCount: 2
  auth: 
    username: admin
    password: agusmarian
    erlangCookie: agusmarian
  metrics:
    enabled: true
    serviceMonitor: 
      enabled: true
      namespace: default      
    prometheusRule: enabled