apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      role: status-worker
  template:
    metadata:
      labels:
        role: status-worker
    spec:
      containers:
      - name: status-worker
        image: image_tag
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBIT_HOST
          value: "rabbitmq-service"  
        - name: REDIS_HOST
          value: "redis-cluster-app"          
        #ports:
        #- containerPort: 8080
        #readinessProbe:
        #  httpGet:
        #    path: /health
        #    port: 8080
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
        #livenessProbe:
        #  tcpSocket:
        #    port: 8080
        #  initialDelaySeconds: 15
        #  periodSeconds: 20
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
