prometheus-adapter:
  prometheus:
    url: http://prometheus-app-server.default.svc.cluster.local
    port: 80
  rbac:
    create: true

  serviceAccount:
    create: true

  service:
    port: 443

  logLevel: 6
  rules:
  default: false
  external:
    - seriesQuery: '{name=~"^rabbitmqqueue.*"}'
      resources:
        #template: <<.Resource>>
        overrides:
          namespace:
            resource: namespace
          service:
            resource: service
          pod:
            resource: pod
      name:
        matches: ""
        as: "rabbitmq_queue_messages_ready"
      metricsQuery: 'rate(<<.Series>>{<<.LabelMatchers>>}[1m])'