prometheus-adapter:
  prometheus:
    url: http://prometheus-app-server.default.svc.cluster.local
    port: 80
  rbac:
    create: true

  serviceAccount:
    create: true

  service:
    port: 443

  logLevel: 6
  rules:
    custom:
    - seriesQuery: 'rabbitmq_queue_messages{app_kubernetes_io_instance="rabbitmq-cluster-app",app_kubernetes_io_managed_by="Helm",app_kubernetes_io_name="rabbitmq",controller_revision_hash="rabbitmq-cluster-app-7c8db6c76c",helm_sh_chart="rabbitmq-8.19.2",instance="192.168.84.251:9419",job="kubernetes-pods",kubernetes_namespace="default",kubernetes_pod_name="rabbitmq-cluster-app-1",queue="prueba",statefulset_kubernetes_io_pod_name="rabbitmq-cluster-app-1",vhost="/"}'
      #resources:
      #  template: <<.Resource>>
      name:
        #matches: ""
        as: "rabbitmq_queue_messages"
      metricsQuery: count(rabbitmq_queue_messages{app_kubernetes_io_instance="rabbitmq-cluster-app",app_kubernetes_io_managed_by="Helm",app_kubernetes_io_name="rabbitmq",controller_revision_hash="rabbitmq-cluster-app-7c8db6c76c",helm_sh_chart="rabbitmq-8.19.2",instance="192.168.84.251:9419",job="kubernetes-pods",kubernetes_namespace="default",kubernetes_pod_name="rabbitmq-cluster-app-1",queue="prueba",statefulset_kubernetes_io_pod_name="rabbitmq-cluster-app-1",vhost="/"})