prometheus-adapter:
  prometheus:
    url: http://prometheus-app-server.default.svc.cluster.local
    port: 80
  rbac:
    create: true

  serviceAccount:
    create: true

  service:
    port: 443

  logLevel: 6
  rules:
    custom:
    - seriesQuery: '{__name__=~"^some_metric_count$"}'
      resources:
        template: <<.Resource>>
      name:
        matches: ""
        as: "my_custom_metric"
      metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)