prometheus-adapter:
  prometheus:
    url: http://prometheus-app-server.default.svc.cluster.local
    port: 80
  rbac:
    create: true

  serviceAccount:
    create: true

  service:
    port: 443

  logLevel: 6
  rules:
    seriesQuery: 'rabbitmq_queue_messages{kubernetes_pod_name!="",kubernetes_namespace!=""}'
    #default: false
    #custom:
    #- seriesQuery: 'rabbitmq_queue_messages{kubernetes_pod_name!="",kubernetes_namespace!=""}'    
      #metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>,queue="prueba"}) by (<<.GroupBy>>)