prometheus:
  serverFiles:
    recording_rules.yml:
      groups:
        - name: rabbitmq_queue_messages_totals
          rules:
          - record: rabbitmq_queue_messages_cluster_appliers:sum
            expr: sum(rabbitmq_queue_messages{queue=~".*.cluster-appliers"})