prometheus:
  server:
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 512Mi
  serverFiles:
    recording_rules.yml:
      groups:
        - name: rabbitmq_queue_messages_totals
          rules:
          - record: rabbitmq_queue_messages_cluster_appliers
            expr: sum(rabbitmq_queue_messages{queue=~".*.cluster-appliers"})
            labels:
              kubernetes_namespace: default
              app_kubernetes_io_instance: rabbitmq-cluster-app
          - record: rabbitmq_queue_messages_status_workers
            expr: sum(rabbitmq_queue_messages{queue=~".*.status-workers"})
            labels:
              kubernetes_namespace: default
              app_kubernetes_io_instance: rabbitmq-cluster-app
          - record: rabbitmq_queue_messages_yaml_managers
            expr: sum(rabbitmq_queue_messages{queue=~".*.yaml-managers"})                               
            labels:
              kubernetes_namespace: default
              app_kubernetes_io_instance: rabbitmq-cluster-app
          - record: rate_nginx_ingress_controller_nginx_process_requests_total
            expr: rate(nginx_ingress_controller_nginx_process_requests_total[2m])
            labels:
              kubernetes_namespace: default
              app_kubernetes_io_instance: ingress-nginx-app-controller