fluent-bit:
  config: 
    outputs: |
      [OUTPUT]
          Name http
          Match kube.*
          Host logstash-app-logstash-headless
          Logstash_Format On
          Retry_Limit False

      [OUTPUT]
          Name http
          Match host.*
          Host logstash-app-logstash-headless
          Logstash_Format On
          Retry_Limit False