redis-cluster:
  service:
    type: LoadBalancer
    annotations: 
      networking.gke.io/load-balancer-type: "Internal"
      external-dns.alpha.kubernetes.io/hostname: redis-service.framework.services.gcp.com.ar.
  global:
    redis:
      password: agusmarian 
  