apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
spec:
  replicas: 2
  selector:
    matchLabels:
      role: entrypoint
  template:
    metadata:
      labels:
        role: entrypoint
    spec:
      containers:
      - name: entrypoint
        image: image_tag
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080
        env:
        - name: RABBIT_HOST
          value: "rabbitmq-service" 
        - name: STATUS_SERVICE_URL
          value: "http://status-worker-service"   
        #readinessProbe:
        #  httpGet:
        #    path: /health
        #    port: 8080
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
        #livenessProbe:
        #  tcpSocket:
        #    port: 8080
        #  initialDelaySeconds: 15
        #  periodSeconds: 20
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
