apiVersion: apps/v1
kind: Deployment
metadata:
  name: receptionist
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: receptionist
  template:
    metadata:
      labels:
        role: receptionist
    spec:
      containers:
      - image: agustinnormand/tpi_receptionist:6817d43441214397f6a8076b2042abcb11ffc980
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 8080
        name: receptionist
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
