rabbitmq:
  replicaCount: 3
  auth:
    username: guest
    password: guest
  service:
    type: LoadBalancer
    annotations: 
      networking.gke.io/load-balancer-type: "Internal"
      external-dns.alpha.kubernetes.io/hostname: rabbitmq-service.framework.services.gcp.com.ar.