name: Cluster-Applier

env:
  ENV_CODE_PATH: 'management-app/cluster-applier/*'
  ENV_DOCKER_PATH: 'Docker/Cluster-Applier/*'
  ENV_WORKING_DIRECTORY: management-app/cluster-applier/
  ENV_JAR_PATH: ./target/cluster-applier-0.0.1-SNAPSHOT.jar
  ENV_JAR_DOCKER_PATH: ../../Docker/Cluster-Applier/Cluster-Applier.jar
  ENV_CREDENTIALS_FILE_PATH: "Docker/Cluster-Applier/credentials.json"
  ENV_DOCKER_CONTEXT: ./Docker/Cluster-Applier/
  ENV_DOCKERFILE_PATH: ./Docker/Cluster-Applier/Dockerfile
  ENV_IMAGE_TAGS: ${{ secrets.DOCKER_USERNAME }}/tpi_cluster_applier:latest, ${{ secrets.DOCKER_USERNAME }}/tpi_cluster_applier:${{ github.sha }}
  ENV_KUSTOMIZE_PATH: ../../kustomize/Cluster-Applier/
  ENV_KUSTOMIZE_OUTPUT_FILE: "Kubernetes/Management/03-cluster-applier-deployment.yaml"
  ENV_COMMIT_PATH: './Kubernetes/Management/'
  ENV_KUSTOMIZE_BUILD_DIR: './kustomize/Cluster-Applier/'
  ENV_KUSTOMIZE_COMMAND: kustomize edit set image image_tag=${{ secrets.DOCKER_USERNAME }}/tpi_cluster_applier:$GITHUB_SHA

on:
  push:
    paths:
    - 'management-app/cluster-applier/**'
    - 'Docker/Cluster-Applier/*'

defaults:
  run:
    working-directory: management-app/cluster-applier/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 15
      - name: Install local library
        run: |
          cd ../commons/
          mvn install
          cd -
      - name: Build with Maven
        run:
          mvn clean package --file pom.xml
      - name: Move jar to Dockerfile context
        run: mv ./target/cluster-applier-0.0.1-SNAPSHOT.jar ../../Docker/Cluster-Applier/Cluster-Applier.jar
 
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Create credentials file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "Docker/Cluster-Applier/credentials.json"
          FILE_DATA: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: build and push Docker image
        uses: docker/build-push-action@v2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          context: ./Docker/Cluster-Applier/
          file: ./Docker/Cluster-Applier/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tpi_cluster_applier:latest, ${{ secrets.DOCKER_USERNAME }}/tpi_cluster_applier:${{ github.sha }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
         cd ../../kustomize/Cluster-Applier/
         kustomize edit set image image_tag=${{ secrets.DOCKER_USERNAME }}/tpi_cluster_applier:$GITHUB_SHA

      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '3.0.0'
          kustomize_build_dir: './kustomize/Cluster-Applier/'
          kustomize_comment: true
          kustomize_output_file: "Kubernetes/Management/03-cluster-applier-deployment.yaml"
          kustomize_build_options: "--load_restrictor none"
          enable_alpha_plugins: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          path: './Kubernetes/Management/'
