name: Entrypoint

on:
  push:
    paths:
    - 'management-app/entrypoint/**'
    - 'Docker/Entrypoint/*'

defaults:
  run:
    working-directory: management-app/entrypoint/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 15
      - name: Install local library
        run: |
          cd ../commons/
          mvn install
          cd -
      - name: Build with Maven
        run:
          mvn clean package --file pom.xml
      - name: Move jar to Dockerfile context
        run: mv ./target/entrypoint-0.0.1-SNAPSHOT.jar ../../Docker/Entrypoint/Entrypoint.jar
 
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Create credentials file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "Docker/Entrypoint/credentials.json"
          FILE_DATA: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: build and push Docker image
        uses: docker/build-push-action@v2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          context: ./Docker/Entrypoint/
          file: ./Docker/Entrypoint/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tpi_entrypoint:latest, ${{ secrets.DOCKER_USERNAME }}/tpi_entrypoint:${{ github.sha }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
         cd ../../kustomize/Entrypoint/
         kustomize edit set image image_tag=${{ secrets.DOCKER_USERNAME }}/tpi_entrypoint:$GITHUB_SHA

      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '3.0.0'
          kustomize_build_dir: './kustomize/Entrypoint/'
          kustomize_comment: true
          kustomize_output_file: "Kubernetes/Management/01-entrypoint-deployment.yaml"
          kustomize_build_options: "--load_restrictor none"
          enable_alpha_plugins: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          path: './Kubernetes/Management/'
