name: Status-Worker

env:
  ENV_CODE_PATH: 'management-app/status-worker/*'
  ENV_DOCKER_PATH: 'Docker/Status-Worker/*'
  ENV_WORKING_DIRECTORY: management-app/status-worker/
  ENV_JAR_PATH: ./target/status-worker-0.0.1-SNAPSHOT.jar
  ENV_JAR_DOCKER_PATH: ../../Docker/Status-Worker/Status-Worker.jar
  ENV_DOCKER_CONTEXT: ./Docker/Status-Worker/
  ENV_DOCKERFILE_PATH: ./Docker/Status-Worker/Dockerfile
  ENV_IMAGE_TAGS: $DOCKER_USERNAME/tpi_status-worker:latest, $DOCKER_USERNAME/tpi_status-worker:${{ github.sha }}
  ENV_KUSTOMIZE_PATH: ../../kustomize/Status-Worker/
  ENV_KUSTOMIZE_OUTPUT_FILE: "Kubernetes/Management/01-status-worker-deployment.yaml"
  ENV_COMMIT_PATH: './Kubernetes/Management/'
  ENV_KUSTOMIZE_BUILD_DIR: './kustomize/Status-Worker/'
  ENV_KUSTOMIZE_COMMAND: kustomize edit set image image_tag=$DOCKER_USERNAME/tpi_status-worker:$GITHUB_SHA

on:
  push:
    paths:
    - 'management-app/status-worker/*'
    - 'Docker/Status-Worker/*'

defaults:
  run:
    working-directory: management-app/status-worker/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 15
      - name: Install local library
        run: |
          cd ../commons/
          mvn install
          cd -
      - name: Build with Maven
        run:
          mvn clean package --file pom.xml
      - name: Move jar to Dockerfile context
        run: mv ./target/status-worker-0.0.1-SNAPSHOT.jar ../../Docker/Status-Worker/Status-Worker.jar
 
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build and push Docker image
        uses: docker/build-push-action@v2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          context: ./Docker/Status-Worker/
          file: ./Docker/Status-Worker/Dockerfile
          push: true
          tags: $DOCKER_USERNAME/tpi_status-worker:latest, $DOCKER_USERNAME/tpi_status-worker:${{ github.sha }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
         cd ../../kustomize/Status-Worker/
         kustomize edit set image image_tag=$DOCKER_USERNAME/tpi_status-worker:$GITHUB_SHA

      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '3.0.0'
          kustomize_build_dir: './kustomize/Status-Worker/'
          kustomize_comment: true
          kustomize_output_file: "Kubernetes/Management/01-status-worker-deployment.yaml"
          kustomize_build_options: "--load_restrictor none"
          enable_alpha_plugins: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          path: './Kubernetes/Management/'
